### ISSUE TITLE
Black screen crash on launch

### ISSUE THREAD

**Issue by Dave247** [Rattpak/T6SP-Mod-Release#1]
My issue isn't strictly related to the mod, but i am hoping that someone smarter then I am will be able to help. 

Trying to run the game from the vanilla executable results in a black screen, before the game closes with no error message, nor anything even logged in the Event Viewer. Trying to run it through the mod executable instead still acts the same, but at least there is an entry in the event viewer that is better then nothing. As I really do not want to just randomly try everything written online, only for nothing to work.

I'm on Windows 11, so I'm sure it's some dumb compatibility issue to do with some minor thing. Also to note it's only the singleplayer that is crashing, the Zombies and Multiplayer launch fine without any issues. 

```Faulting application name: t6sp-mod-launcher.exe, version: 0.0.0.0, time stamp: 0x664bb025
Faulting module name: ucrtbase.dll, version: 10.0.22621.3640, time stamp: 0x84b62951
Exception code: 0xc0000409
Fault offset: 0x0009e3bb
Faulting process id: 0x0x7DB0
Faulting application start time: 0x0x1DB2D161C78535E
Faulting application path: G:\SteamLibrary\steamapps\common\Call of Duty Black Ops II\t6sp-mod-launcher.exe
Faulting module path: C:\Windows\System32\ucrtbase.dll
Report Id: 54b8fe32-c23b-4b4f-b473-9b61b932f79c
Faulting package full name: 
Faulting package-relative application ID: ```

**Comment by Rattpak** [comment]
Add me on discord (rattpak) or join the discord server in the README.md and I can help you there

**Comment by Dave247** [comment]
Thanks for the help. Turns out it was an issue with the CEG DRM, as simply uninstalling and re-downloading the game actually worked for a change.
